# battle_system/weapon.py

from random import randint, choice


class Weapon:
    """A class representing a weapon."""

    def __init__(self, name: str, weapon_type: str, damage: int = 0, value: int = 0, tier: str = "low", cycle:int = 0) -> None:
        self.name = name
        self.weapon_type = weapon_type
        self.damage = damage
        self.dmg_min = int(damage * 0.7)  # Minimum damage (70% of base damage)
        self.dmg_max = int(damage * 1.3)  # Maximum damage (130% of base damage)
        self.value = value
        self.tier = tier
        self.cycle = cycle  # Added cycle attribute

    def get_display_name(self):
        """Returns the weapon name adjusted for the cycle."""
        if self.cycle == 0:
            return self.name
        elif self.cycle == 1:
            return f"{self.name}+"
        else:
            return f"{self.name}+{self.cycle}"

def generate_weapon(tier: str, cycle: int = 0) -> Weapon:
    """Generates a weapon based on the specified tier."""
    weapon_lists = {
        "low": low_tier_weapons,
        "mid": mid_tier_weapons,
        "high": high_tier_weapons
    }
    tier_stats = {
        "low": {
            "damage_range": (3, 6),
            "value_range": (5, 10)
        },
        "mid": {
            "damage_range": (7, 12),
            "value_range": (15, 25)
        },
        "high": {
            "damage_range": (13, 20),
            "value_range": (30, 50)
        }
    }
    weapon_list = weapon_lists.get(tier)
    stats = tier_stats.get(tier)
    if not weapon_list or not stats:
        raise ValueError("Invalid tier for weapon generation")

    # Select a random weapon from the tier's weapon list
    weapon_template = choice(weapon_list)
    
    # Generate damage and value within the tier's range
    damage = randint(*stats['damage_range'])
    value = randint(*stats['value_range'])
    # Scale damage and value with cycle
    damage = int(damage * (1 + 0.2 * cycle))
    value = int(value * (1 + 0.2 * cycle))
    # Adjust weapon name
    weapon_name = weapon_template.name
    if cycle == 1:
        weapon_name += '+'
    elif cycle > 1:
        weapon_name += f'+{cycle}'
    # Create the weapon with the adjusted name
    return Weapon(
        name=weapon_name,
        weapon_type=weapon_template.weapon_type,
        damage=damage,
        value=value,
        tier=tier,
        cycle=cycle
    )

# Add a method to scale boss weapon values with cycle

def scale_weapon_for_cycle(weapon, cycle):
    """Scales a weapon's stats based on the New Game+ cycle."""
    if not hasattr(weapon, 'cycle_scaled') or not weapon.cycle_scaled:
        # Scale damage
        weapon.damage = int(weapon.damage * (1 + 0.2 * cycle))
        weapon.dmg_min = int(weapon.dmg_min * (1 + 0.2 * cycle))
        weapon.dmg_max = int(weapon.dmg_max * (1 + 0.2 * cycle))
        
        # Scale value - boss weapons should start at 50 gold
        if weapon.tier == 'boss' and weapon.value < 50:
            weapon.value = 50
        
        # Apply cycle scaling to value
        weapon.value = int(weapon.value * (1 + 0.2 * cycle))
        
        # Mark as scaled to prevent duplicate scaling
        weapon.cycle_scaled = True
        
        # Update name with cycle indicator if cycle > 0
        if cycle > 0 and '+' not in weapon.name:
            if cycle == 1:
                weapon.name += '+'
            else:
                weapon.name += f'+{cycle}'
    
    return weapon

# Weapon lists per tier, with Weapon instances containing name and weapon_type

# Low-tier weapons (natural and normal)
low_tier_weapons_norm = [
    Weapon(name="Dagger", weapon_type="sharp"),
    Weapon(name="Club", weapon_type="blunt"),
    Weapon(name="Short Bow", weapon_type="ranged"),
    Weapon(name="Fists", weapon_type="blunt"),
    Weapon(name="Hand Axe", weapon_type="sharp"),
    Weapon(name="Sling", weapon_type="ranged"),
    Weapon(name="Hatchet", weapon_type="sharp"),
    Weapon(name="Wooden Spear", weapon_type="sharp"),
    Weapon(name="Rusty Sword", weapon_type="sharp"),
    Weapon(name="Throwing Stone", weapon_type="blunt"),
    Weapon(name="Peasant's Sickle", weapon_type="sharp"),
    Weapon(name="Training Sword", weapon_type="sharp"),
    Weapon(name="Pitchfork", weapon_type="sharp"),
    Weapon(name="Wooden Mace", weapon_type="blunt"),
    Weapon(name="Makeshift Dagger", weapon_type="sharp"),
    Weapon(name="Bronze Knife", weapon_type="sharp"),
    Weapon(name="Short Staff", weapon_type="staff"),
    Weapon(name="Stone Hammer", weapon_type="blunt"),
    Weapon(name="Bone Club", weapon_type="blunt"),
    Weapon(name="Throwing Dart", weapon_type="ranged"),
    Weapon(name="Wooden Flail", weapon_type="flail"),
    Weapon(name="Farm Hoe", weapon_type="sharp"),
    Weapon(name="Rusty Crossbow", weapon_type="ranged"),
    Weapon(name="Splintered Axe", weapon_type="sharp"),
    Weapon(name="Iron Shard", weapon_type="sharp"),
    Weapon(name="Thorn Whip", weapon_type="whip"),
    Weapon(name="Small Hatchet", weapon_type="sharp"),
    Weapon(name="Stone Hatchet", weapon_type="sharp"),
    Weapon(name="Bone Dagger", weapon_type="sharp"),
    Weapon(name="Rusty Scythe", weapon_type="scythe"),
    Weapon(name="Pewter Club", weapon_type="blunt"),
    Weapon(name="Iron Hook", weapon_type="hook"),
    Weapon(name="Splintered Spear", weapon_type="sharp"),
    Weapon(name="Farmer's Spade", weapon_type="blunt"),
    Weapon(name="Throwing Pebble", weapon_type="ranged"),
    Weapon(name="Makeshift Sling", weapon_type="ranged"),
    Weapon(name="Bronze Shortsword", weapon_type="sharp"),
    Weapon(name="Wooden Cudgel", weapon_type="blunt"),
    Weapon(name="Shepherd's Staff", weapon_type="staff"),
    Weapon(name="Spike Club", weapon_type="blunt"),
    Weapon(name="Flint Knife", weapon_type="sharp"),
    Weapon(name="Iron Spike", weapon_type="sharp"),
    Weapon(name="Small Throwing Axe", weapon_type="ranged"),
    Weapon(name="Reed Spear", weapon_type="sharp"),
    Weapon(name="Weighted Stick", weapon_type="blunt"),
    Weapon(name="Carpenter's Mallet", weapon_type="blunt"),
    Weapon(name="Small Pickaxe", weapon_type="sharp"),
    Weapon(name="Wooden Javelin", weapon_type="ranged"),
    Weapon(name="Brick Sling", weapon_type="ranged"),
    Weapon(name="Stone-Edged Flail", weapon_type="flail"),
    Weapon(name="Iron Tipped Cane", weapon_type="blunt"),
    Weapon(name="Garden Shears", weapon_type="sharp"),
    Weapon(name="Broken Sword", weapon_type="sharp"),
    Weapon(name="Training Club", weapon_type="blunt"),
    Weapon(name="Pointed Stick", weapon_type="sharp"),
    Weapon(name="Primitive Shovel", weapon_type="blunt"),
    Weapon(name="Rope Sling", weapon_type="ranged"),
    Weapon(name="Clay Brick", weapon_type="blunt"),
    Weapon(name="Jagged Shard", weapon_type="sharp"),
    Weapon(name="Rusty Pitchfork", weapon_type="sharp"),
    Weapon(name="Brass Knuckles", weapon_type="blunt"),
    Weapon(name="Rusted Hatchet", weapon_type="sharp"),
    Weapon(name="Bronze Gladius", weapon_type="sharp"),
    Weapon(name="Stone Thrower", weapon_type="ranged"),
    Weapon(name="Sharpened Bone", weapon_type="sharp"),
    Weapon(name="Fisherman's Gaff", weapon_type="hook"),
    Weapon(name="Ornate Stick", weapon_type="blunt"),
    Weapon(name="Pebble Sling", weapon_type="ranged"),
    Weapon(name="Wooden Pike", weapon_type="sharp"),
    Weapon(name="Leather Whip", weapon_type="whip"),
    Weapon(name="Iron Plated Knuckles", weapon_type="blunt"),
    Weapon(name="Stone Club", weapon_type="blunt"),
    Weapon(name="Iron Poker", weapon_type="sharp"),
    Weapon(name="Garden Hoe", weapon_type="sharp"),
    Weapon(name="Gutter Knife", weapon_type="sharp"),
    Weapon(name="Iron Trowel", weapon_type="sharp"),
    Weapon(name="Kitchen Cleaver", weapon_type="sharp"),
    Weapon(name="Small Mace", weapon_type="blunt"),
    Weapon(name="Rough Scythe", weapon_type="scythe"),
    Weapon(name="Training Mace", weapon_type="blunt"),
    Weapon(name="Brickbat", weapon_type="blunt"),
    Weapon(name="Old Crossbow", weapon_type="ranged"),
    Weapon(name="Simple Javelin", weapon_type="ranged"),
    Weapon(name="Farmyard Rake", weapon_type="sharp"),
    Weapon(name="Brass Handbell", weapon_type="blunt"),
    Weapon(name="Iron Cosh", weapon_type="blunt"),
    Weapon(name="Throwing Star", weapon_type="ranged"),
    Weapon(name="Peasant Flail", weapon_type="flail"),
    Weapon(name="Wooden Bo Staff", weapon_type="staff"),
    Weapon(name="Butcher's Cleaver", weapon_type="sharp"),
    Weapon(name="Wagon Wheel Spoke", weapon_type="blunt")
]

low_tier_weapons_nat = [
    Weapon(name="Bounce", weapon_type="natural"),
    Weapon(name="Tail Whip", weapon_type="natural"),
    Weapon(name="Bites", weapon_type="natural"),
    Weapon(name="Tentacle Slap", weapon_type="natural"),
    Weapon(name="Bone Claws", weapon_type="natural"),
    Weapon(name="Spiked Carapace", weapon_type="natural"),
    Weapon(name="Venomous Fangs", weapon_type="natural"),
    Weapon(name="Corrupted Vine", weapon_type="natural"),
    Weapon(name="Acidic Touch", weapon_type="natural"),
    Weapon(name="Ghoul Claws", weapon_type="natural"),
    Weapon(name="Fiery Peck", weapon_type="natural"),
    Weapon(name="Swarm Sting", weapon_type="natural"),
    Weapon(name="Barbed Spit", weapon_type="natural"),
    Weapon(name="Venomous Barb", weapon_type="natural"),
    Weapon(name="Spiny Lash", weapon_type="natural"),
    Weapon(name="Jagged Talon", weapon_type="natural"),
    Weapon(name="Vine Strike", weapon_type="natural"),
    Weapon(name="Mud Fist", weapon_type="natural"),
    Weapon(name="Acid Splash", weapon_type="natural"),
    Weapon(name="Infernal Spit", weapon_type="natural"),
    Weapon(name="Mucus Spray", weapon_type="natural"),
    Weapon(name="Shadow Bite", weapon_type="natural"),
    Weapon(name="Toxic Breath", weapon_type="natural"),
    Weapon(name="Stinger Strike", weapon_type="natural"),
    Weapon(name="Fungal Slap", weapon_type="natural"),
    Weapon(name="Rock Crush", weapon_type="natural"),
    Weapon(name="Blighted Touch", weapon_type="natural"),
    Weapon(name="Spore Burst", weapon_type="natural"),
    Weapon(name="Iron Fangs", weapon_type="natural"),
    Weapon(name="Talon Swipe", weapon_type="natural"),
    Weapon(name="Infected Bite", weapon_type="natural"),
    Weapon(name="Chitin Bash", weapon_type="natural"),
    Weapon(name="Mire Lash", weapon_type="natural"),
    Weapon(name="Shambling Slam", weapon_type="natural"),
    Weapon(name="Screech", weapon_type="natural"),
    Weapon(name="Blinding Spit", weapon_type="natural"),
    Weapon(name="Toxic Needle", weapon_type="natural"),
    Weapon(name="Ichor Strike", weapon_type="natural"),
    Weapon(name="Jagged Spine", weapon_type="natural"),
    Weapon(name="Poison Talons", weapon_type="natural"),
    Weapon(name="Mud Tendril", weapon_type="natural"),
    Weapon(name="Bloodied Maw", weapon_type="natural"),
    Weapon(name="Lacerating Claws", weapon_type="natural"),
    Weapon(name="Crushing Pincer", weapon_type="natural"),
    Weapon(name="Writhing Lash", weapon_type="natural"),
    Weapon(name="Barbed Tongue", weapon_type="natural"),
    Weapon(name="Battering Horns", weapon_type="natural"),
    Weapon(name="Gooey Strike", weapon_type="natural"),
    Weapon(name="Iron Bark", weapon_type="natural"),
    Weapon(name="Jagged Maw", weapon_type="natural"),
    Weapon(name="Piercing Thorn", weapon_type="natural"),
    Weapon(name="Bone Bite", weapon_type="natural"),
    Weapon(name="Entangling Roots", weapon_type="natural"),
    Weapon(name="Scaly Slam", weapon_type="natural"),
    Weapon(name="Blistering Spit", weapon_type="natural"),
    Weapon(name="Crushing Hoof", weapon_type="natural"),
    Weapon(name="Brimstone Peck", weapon_type="natural"),
    Weapon(name="Shadow Swipe", weapon_type="natural"),
    Weapon(name="Gnarled Claw", weapon_type="natural"),
    Weapon(name="Putrid Breath", weapon_type="natural"),
    Weapon(name="Crawling Claw", weapon_type="natural"),
    Weapon(name="Rending Bite", weapon_type="natural"),
    Weapon(name="Needle Spine", weapon_type="natural"),
    Weapon(name="Warped Claw", weapon_type="natural"),
    Weapon(name="Acid Bloom", weapon_type="natural"),
    Weapon(name="Thorny Embrace", weapon_type="natural"),
    Weapon(name="Thick Spittle", weapon_type="natural"),
    Weapon(name="Dark Maw", weapon_type="natural"),
    Weapon(name="Twisted Vine", weapon_type="natural"),
    Weapon(name="Venom Lash", weapon_type="natural"),
    Weapon(name="Spike Shield", weapon_type="natural"),
    Weapon(name="Scalding Spray", weapon_type="natural"),
    Weapon(name="Flaming Tail", weapon_type="natural"),
    Weapon(name="Boulder Throw", weapon_type="natural"),
    Weapon(name="Rotten Bite", weapon_type="natural"),
    Weapon(name="Serrated Stinger", weapon_type="natural"),
    Weapon(name="Tusk Gore", weapon_type="natural"),
    Weapon(name="Blight Claw", weapon_type="natural"),
    Weapon(name="Briar Thorns", weapon_type="natural"),
    Weapon(name="Warped Branch", weapon_type="natural"),
    Weapon(name="Leeching Maw", weapon_type="natural"),
    Weapon(name="Sonic Screech", weapon_type="natural"),
    Weapon(name="Tremor Slam", weapon_type="natural"),
    Weapon(name="Scorched Peck", weapon_type="natural"),
    Weapon(name="Tethered Spike", weapon_type="natural"),
    Weapon(name="Infectious Claws", weapon_type="natural")
]

low_tier_weapons = low_tier_weapons_norm + low_tier_weapons_nat

# Mid-tier weapons (natural and normal)
mid_tier_weapons_norm = [
    Weapon(name="Iron Sword", weapon_type="sharp"),
    Weapon(name="Scimitar", weapon_type="sharp"),
    Weapon(name="Mace", weapon_type="blunt"),
    Weapon(name="Crossbow", weapon_type="ranged"),
    Weapon(name="Quarterstaff", weapon_type="staff"),
    Weapon(name="Morningstar", weapon_type="blunt"),
    Weapon(name="Battle Axe", weapon_type="sharp"),
    Weapon(name="Javelin", weapon_type="ranged"),
    Weapon(name="Light Crossbow", weapon_type="ranged"),
    Weapon(name="Flail", weapon_type="flail"),
    Weapon(name="Steel Rapier", weapon_type="sharp"),
    Weapon(name="Steel Warhammer", weapon_type="blunt"),
    Weapon(name="Longbow", weapon_type="ranged"),
    Weapon(name="Reinforced Club", weapon_type="blunt"),
    Weapon(name="Iron Trident", weapon_type="sharp"),
    Weapon(name="Steel Dagger", weapon_type="sharp"),
    Weapon(name="Knight's Mace", weapon_type="blunt"),
    Weapon(name="Poleaxe", weapon_type="sharp"),
    Weapon(name="Throwing Axe", weapon_type="ranged"),
    Weapon(name="Arbalest", weapon_type="ranged"),
    Weapon(name="Steel Pike", weapon_type="sharp"),
    Weapon(name="Bastard Sword", weapon_type="sharp"),
    Weapon(name="Heavy Mace", weapon_type="blunt"),
    Weapon(name="Saber", weapon_type="sharp"),
    Weapon(name="Halberd", weapon_type="sharp"),
    Weapon(name="Falchion", weapon_type="sharp"),
    Weapon(name="Heavy Sling", weapon_type="ranged"),
    Weapon(name="Spiked Flail", weapon_type="flail"),
    Weapon(name="Steel Morningstar", weapon_type="blunt"),
    Weapon(name="Short Pike", weapon_type="sharp"),
    Weapon(name="Broad Axe", weapon_type="sharp"),
    Weapon(name="Steel Javelin", weapon_type="ranged"),
    Weapon(name="Executioner's Axe", weapon_type="sharp"),
    Weapon(name="Chain Whip", weapon_type="whip"),
    Weapon(name="Flanged Mace", weapon_type="blunt"),
    Weapon(name="Glaive", weapon_type="sharp"),
    Weapon(name="Reinforced Staff", weapon_type="staff"),
    Weapon(name="Iron Hook", weapon_type="hook"),
    Weapon(name="War Pick", weapon_type="sharp"),
    Weapon(name="Double-headed Axe", weapon_type="sharp"),
    Weapon(name="Steel Club", weapon_type="blunt"),
    Weapon(name="Double Flail", weapon_type="flail"),
    Weapon(name="Chained Morningstar", weapon_type="blunt"),
    Weapon(name="Battle Scythe", weapon_type="scythe"),
    Weapon(name="Mounted Lance", weapon_type="sharp"),
    Weapon(name="Stiletto", weapon_type="sharp"),
    Weapon(name="Heavy Crossbow", weapon_type="ranged"),
    Weapon(name="Bladed Staff", weapon_type="staff"),
    Weapon(name="Knight's Flail", weapon_type="flail"),
    Weapon(name="Duelist's Rapier", weapon_type="sharp"),
    Weapon(name="Weighted Net", weapon_type="ranged"),
    Weapon(name="Hooked Polearm", weapon_type="hook"),
    Weapon(name="Iron Talwar", weapon_type="sharp"),
    Weapon(name="Military Fork", weapon_type="sharp"),
    Weapon(name="Trident Spear", weapon_type="sharp"),
    Weapon(name="Siege Crossbow", weapon_type="ranged"),
    Weapon(name="Steel Short Sword", weapon_type="sharp"),
    Weapon(name="Footman’s Flail", weapon_type="flail"),
    Weapon(name="War Mattock", weapon_type="sharp"),
    Weapon(name="Heavy Hammer", weapon_type="blunt"),
    Weapon(name="Parrying Dagger", weapon_type="sharp"),
    Weapon(name="Ranseur", weapon_type="sharp"),
    Weapon(name="Bidenhander", weapon_type="sharp"),
    Weapon(name="Steel Maul", weapon_type="blunt"),
    Weapon(name="Stinger Whip", weapon_type="whip"),
    Weapon(name="Repeating Crossbow", weapon_type="ranged"),
    Weapon(name="Iron Halberd", weapon_type="sharp"),
    Weapon(name="Spiked Mace", weapon_type="blunt"),
    Weapon(name="Slashing Saber", weapon_type="sharp"),
    Weapon(name="Knight's Broadsword", weapon_type="sharp"),
    Weapon(name="Crusader’s Sword", weapon_type="sharp"),
    Weapon(name="Steel Polearm", weapon_type="sharp"),
    Weapon(name="Plated Knuckles", weapon_type="blunt"),
    Weapon(name="Bladed Glaive", weapon_type="sharp"),
    Weapon(name="Two-Pronged Fork", weapon_type="sharp"),
    Weapon(name="Battle Fork", weapon_type="sharp"),
    Weapon(name="Fortress Crossbow", weapon_type="ranged"),
    Weapon(name="Iron Studded Mace", weapon_type="blunt"),
    Weapon(name="Double-ended Spear", weapon_type="sharp"),
    Weapon(name="Grapple Hook", weapon_type="hook"),
    Weapon(name="Mercenary Axe", weapon_type="sharp"),
    Weapon(name="Chained Hook", weapon_type="hook"),
    Weapon(name="Steel Whip", weapon_type="whip"),
    Weapon(name="Enforcer's Cudgel", weapon_type="blunt"),
    Weapon(name="Long Scythe", weapon_type="scythe"),
    Weapon(name="Heavy Pickaxe", weapon_type="sharp"),
    Weapon(name="Dragonbone Staff", weapon_type="staff"),
    Weapon(name="Iron Bident", weapon_type="sharp"),
    Weapon(name="Two-Handed Mace", weapon_type="blunt"),
    Weapon(name="Weighted Chain", weapon_type="flail"),
    Weapon(name="Pike Spear", weapon_type="sharp"),
    Weapon(name="Trapper’s Hook", weapon_type="hook"),
    Weapon(name="Tower Crossbow", weapon_type="ranged")
]

mid_tier_weapons_nat = [
    Weapon(name="Tentacles", weapon_type="natural"),
    Weapon(name="Claws", weapon_type="natural"),
    Weapon(name="Stinger", weapon_type="natural"),
    Weapon(name="Horns", weapon_type="natural"),
    Weapon(name="Pincer", weapon_type="natural"),
    Weapon(name="Eldritch Tendril", weapon_type="natural"),
    Weapon(name="Shadow Bite", weapon_type="natural"),
    Weapon(name="Crawling Chaos Spikes", weapon_type="natural"),
    Weapon(name="Cursed Vine", weapon_type="natural"),
    Weapon(name="Ravenous Maw", weapon_type="natural"),
    Weapon(name="Dark Flames", weapon_type="natural"),
    Weapon(name="Obsidian Claw", weapon_type="natural"),
    Weapon(name="Blood Tentacle", weapon_type="natural"),
    Weapon(name="Poisonous Mandibles", weapon_type="natural"),
    Weapon(name="Venomous Lash", weapon_type="natural"),
    Weapon(name="Frosted Talons", weapon_type="natural"),
    Weapon(name="Infernal Bite", weapon_type="natural"),
    Weapon(name="Twisting Roots", weapon_type="natural"),
    Weapon(name="Shadow Spike", weapon_type="natural"),
    Weapon(name="Abyssal Maw", weapon_type="natural"),
    Weapon(name="Thorned Tail", weapon_type="natural"),
    Weapon(name="Fire Spit", weapon_type="natural"),
    Weapon(name="Toxic Fangs", weapon_type="natural"),
    Weapon(name="Webbed Strike", weapon_type="natural"),
    Weapon(name="Warped Horns", weapon_type="natural"),
    Weapon(name="Barbed Tentacle", weapon_type="natural"),
    Weapon(name="Ghostly Swipe", weapon_type="natural"),
    Weapon(name="Serrated Jaw", weapon_type="natural"),
    Weapon(name="Grasping Vine", weapon_type="natural"),
    Weapon(name="Dark Gaze", weapon_type="natural"),
    Weapon(name="Leviathan Strike", weapon_type="natural"),
    Weapon(name="Pestilent Vomit", weapon_type="natural"),
    Weapon(name="Chilling Breath", weapon_type="natural"),
    Weapon(name="Necrotic Claws", weapon_type="natural"),
    Weapon(name="Miasmic Touch", weapon_type="natural"),
    Weapon(name="Wailing Screech", weapon_type="natural"),
    Weapon(name="Pustulent Blight", weapon_type="natural"),
    Weapon(name="Infernal Stomp", weapon_type="natural"),
    Weapon(name="Venomous Thorns", weapon_type="natural"),
    Weapon(name="Entangling Tentacle", weapon_type="natural"),
    Weapon(name="Wyrm Breath", weapon_type="natural"),
    Weapon(name="Wretched Maw", weapon_type="natural"),
    Weapon(name="Razor Barb", weapon_type="natural"),
    Weapon(name="Ichor Lash", weapon_type="natural"),
    Weapon(name="Haunting Claw", weapon_type="natural"),
    Weapon(name="Crimson Tendril", weapon_type="natural"),
    Weapon(name="Grim Claw", weapon_type="natural"),
    Weapon(name="Shadowy Lash", weapon_type="natural"),
    Weapon(name="Gore Bite", weapon_type="natural"),
    Weapon(name="Abyssal Spikes", weapon_type="natural"),
    Weapon(name="Iron Bark Lash", weapon_type="natural"),
    Weapon(name="Serrated Pincer", weapon_type="natural"),
    Weapon(name="Wormtail Lash", weapon_type="natural"),
    Weapon(name="Unholy Slash", weapon_type="natural"),
    Weapon(name="Hellish Gaze", weapon_type="natural"),
    Weapon(name="Molten Bite", weapon_type="natural"),
    Weapon(name="Putrid Talons", weapon_type="natural"),
    Weapon(name="Blistering Claw", weapon_type="natural"),
    Weapon(name="Severing Spike", weapon_type="natural"),
    Weapon(name="Spectral Pincer", weapon_type="natural"),
    Weapon(name="Death Touch", weapon_type="natural"),
    Weapon(name="Corrupted Whip", weapon_type="natural"),
    Weapon(name="Vile Claws", weapon_type="natural"),
    Weapon(name="Plague Touch", weapon_type="natural"),
    Weapon(name="Abyss Fang", weapon_type="natural"),
    Weapon(name="Necrotic Tendril", weapon_type="natural"),
    Weapon(name="Twisting Thorn", weapon_type="natural"),
    Weapon(name="Blighted Hoof", weapon_type="natural"),
    Weapon(name="Cursed Claw", weapon_type="natural"),
    Weapon(name="Molten Tentacle", weapon_type="natural"),
    Weapon(name="Wraith Claw", weapon_type="natural"),
    Weapon(name="Toxic Bloom", weapon_type="natural"),
    Weapon(name="Gore Lash", weapon_type="natural"),
    Weapon(name="Rending Fangs", weapon_type="natural"),
    Weapon(name="Horrific Maw", weapon_type="natural"),
    Weapon(name="Chill Grip", weapon_type="natural"),
    Weapon(name="Warped Stinger", weapon_type="natural"),
    Weapon(name="Withering Vine", weapon_type="natural"),
    Weapon(name="Cavernous Roar", weapon_type="natural"),
    Weapon(name="Hellish Claw", weapon_type="natural"),
    Weapon(name="Magma Breath", weapon_type="natural"),
    Weapon(name="Grasp of Shadows", weapon_type="natural"),
    Weapon(name="Spectral Scythe", weapon_type="natural"),
    Weapon(name="Venom Burst", weapon_type="natural"),
    Weapon(name="Unholy Maw", weapon_type="natural"),
    Weapon(name="Corrosive Claw", weapon_type="natural"),
    Weapon(name="Rotting Grasp", weapon_type="natural"),
    Weapon(name="Dark Surge", weapon_type="natural")
]

mid_tier_weapons = mid_tier_weapons_norm + mid_tier_weapons_nat

# High-tier weapons (natural and normal)
high_tier_weapons_norm = [
    Weapon(name="Long Sword", weapon_type="sharp"),
    Weapon(name="Warhammer", weapon_type="blunt"),
    Weapon(name="Great Hammer", weapon_type="blunt"),
    Weapon(name="Rapier", weapon_type="sharp"),
    Weapon(name="Halberd", weapon_type="sharp"),
    Weapon(name="Heavy Crossbow", weapon_type="ranged"),
    Weapon(name="Double Axe", weapon_type="sharp"),
    Weapon(name="Maul", weapon_type="blunt"),
    Weapon(name="Trident", weapon_type="sharp"),
    Weapon(name="Spiked Chain", weapon_type="chain"),
    Weapon(name="Executioner's Sword", weapon_type="sharp"),
    Weapon(name="Flaming Mace", weapon_type="blunt"),
    Weapon(name="Dragonbone Bow", weapon_type="ranged"),
    Weapon(name="Great Scythe", weapon_type="scythe"),
    Weapon(name="Giant's Club", weapon_type="blunt"),
    Weapon(name="Knight's Halberd", weapon_type="sharp"),
    Weapon(name="Voulge", weapon_type="sharp"),
    Weapon(name="Cross Halberd", weapon_type="sharp"),
    Weapon(name="Battle Flail", weapon_type="flail"),
    Weapon(name="Dwarven Maul", weapon_type="blunt"),
    Weapon(name="Double-ended Axe", weapon_type="sharp"),
    Weapon(name="Dragonfang Sword", weapon_type="sharp"),
    Weapon(name="Meteor Hammer", weapon_type="flail"),
    Weapon(name="Blacksteel Mace", weapon_type="blunt"),
    Weapon(name="Celestial Bow", weapon_type="ranged"),
    Weapon(name="Obsidian Trident", weapon_type="sharp"),
    Weapon(name="Holy Staff", weapon_type="staff"),
    Weapon(name="Doomhammer", weapon_type="blunt"),
    Weapon(name="Inferno Crossbow", weapon_type="ranged"),
    Weapon(name="Paladin's Flail", weapon_type="flail"),
    Weapon(name="Demonbane Rapier", weapon_type="sharp"),
    Weapon(name="Crescent Pike", weapon_type="sharp"),
    Weapon(name="Rune Axe", weapon_type="sharp"),
    Weapon(name="Valiant Spear", weapon_type="sharp"),
    Weapon(name="Storm Bringer", weapon_type="chain"),
    Weapon(name="Thunder Maul", weapon_type="blunt"),
    Weapon(name="Bloodletter Scythe", weapon_type="scythe"),
    Weapon(name="Dragonslayer Sword", weapon_type="sharp"),
    Weapon(name="Colossus Hammer", weapon_type="blunt"),
    Weapon(name="Ethereal Blade", weapon_type="sharp"),
    Weapon(name="Phoenix Bow", weapon_type="ranged"),
    Weapon(name="Storm Pike", weapon_type="sharp"),
    Weapon(name="Hellfire Flail", weapon_type="flail"),
    Weapon(name="Judgement Mace", weapon_type="blunt"),
    Weapon(name="War Trident", weapon_type="sharp"),
    Weapon(name="Frost Halberd", weapon_type="sharp"),
    Weapon(name="Gilded Greatsword", weapon_type="sharp"),
    Weapon(name="Silver Battle Axe", weapon_type="sharp"),
    Weapon(name="Moonlight Staff", weapon_type="staff"),
    Weapon(name="Twinblade", weapon_type="sharp"),
    Weapon(name="Harpoon Crossbow", weapon_type="ranged"),
    Weapon(name="Void Pike", weapon_type="sharp"),
    Weapon(name="Royal Glaive", weapon_type="sharp"),
    Weapon(name="Reaper's Scythe", weapon_type="scythe"),
    Weapon(name="Soul Crusher", weapon_type="blunt"),
    Weapon(name="Dragonfire Crossbow", weapon_type="ranged"),
    Weapon(name="Golden Warhammer", weapon_type="blunt"),
    Weapon(name="Sunblade", weapon_type="sharp"),
    Weapon(name="Warlord's Maul", weapon_type="blunt"),
    Weapon(name="Obsidian Flail", weapon_type="flail"),
    Weapon(name="Lightbringer Pike", weapon_type="sharp"),
    Weapon(name="Dread Axe", weapon_type="sharp"),
    Weapon(name="Mythril Scythe", weapon_type="scythe"),
    Weapon(name="Executioner's Maul", weapon_type="blunt"),
    Weapon(name="Stormcaller Staff", weapon_type="staff"),
    Weapon(name="Raven's Talon", weapon_type="sharp"),
    Weapon(name="Hellion Crossbow", weapon_type="ranged"),
    Weapon(name="Twin Fang", weapon_type="sharp"),
    Weapon(name="Doom Glaive", weapon_type="sharp"),
    Weapon(name="Thunderstrike Hammer", weapon_type="blunt"),
    Weapon(name="Solar Spear", weapon_type="sharp"),
    Weapon(name="Infernal Chain", weapon_type="chain"),
    Weapon(name="Crusader's Flail", weapon_type="flail"),
    Weapon(name="Dragon Hunter Bow", weapon_type="ranged"),
    Weapon(name="Knight's Reaver", weapon_type="sharp"),
    Weapon(name="Skullsplitter", weapon_type="blunt"),
    Weapon(name="Blood Reaver", weapon_type="sharp"),
    Weapon(name="War Scythe", weapon_type="scythe"),
    Weapon(name="Frostbound Hammer", weapon_type="blunt"),
    Weapon(name="Doom Lance", weapon_type="sharp"),
    Weapon(name="Darkflame Trident", weapon_type="sharp"),
    Weapon(name="Judicator's Staff", weapon_type="staff"),
    Weapon(name="Phoenix Claw", weapon_type="sharp"),
    Weapon(name="Serpent's Fang", weapon_type="sharp"),
    Weapon(name="Guardian's Halberd", weapon_type="sharp"),
    Weapon(name="Infernal Maul", weapon_type="blunt"),
    Weapon(name="Tempest Bow", weapon_type="ranged"),
    Weapon(name="Spiked Glaive", weapon_type="sharp"),
    Weapon(name="Sacred Morningstar", weapon_type="blunt"),
    Weapon(name="Necrotic Chain", weapon_type="chain"),
    Weapon(name="Dragon's Wrath", weapon_type="sharp"),
    Weapon(name="Righteous Pike", weapon_type="sharp"),
    Weapon(name="Titan Hammer", weapon_type="blunt"),
    Weapon(name="Celestial Staff", weapon_type="staff")
]

high_tier_weapons_nat = [
    Weapon(name="Acid Spit", weapon_type="natural"),
    Weapon(name="Tail Slam", weapon_type="natural"),
    Weapon(name="Fire Breath", weapon_type="natural"),
    Weapon(name="Necrotic Touch", weapon_type="natural"),
    Weapon(name="Shadow Tentacle", weapon_type="natural"),
    Weapon(name="Eldritch Claw", weapon_type="natural"),
    Weapon(name="Void Strike", weapon_type="natural"),
    Weapon(name="Chaos Bite", weapon_type="natural"),
    Weapon(name="Spectral Fang", weapon_type="natural"),
    Weapon(name="Abyssal Spines", weapon_type="natural"),
    Weapon(name="Nether Lash", weapon_type="natural"),
    Weapon(name="Rift Claw", weapon_type="natural"),
    Weapon(name="Dark Surge", weapon_type="natural"),
    Weapon(name="Wyrm Strike", weapon_type="natural"),
    Weapon(name="Hellfire Breath", weapon_type="natural"),
    Weapon(name="Cursed Spike", weapon_type="natural"),
    Weapon(name="Deathly Roar", weapon_type="natural"),
    Weapon(name="Gloom Grasp", weapon_type="natural"),
    Weapon(name="Putrid Claw", weapon_type="natural"),
    Weapon(name="Infernal Maw", weapon_type="natural"),
    Weapon(name="Spectral Claws", weapon_type="natural"),
    Weapon(name="Abyssal Maw", weapon_type="natural"),
    Weapon(name="Toxic Sludge", weapon_type="natural"),
    Weapon(name="Ethereal Screech", weapon_type="natural"),
    Weapon(name="Chaos Bolt", weapon_type="natural"),
    Weapon(name="Wraith Touch", weapon_type="natural"),
    Weapon(name="Corrupted Bite", weapon_type="natural"),
    Weapon(name="Dark Tendrils", weapon_type="natural"),
    Weapon(name="Soul Rend", weapon_type="natural"),
    Weapon(name="Flesh Ripper", weapon_type="natural"),
    Weapon(name="Fiery Gaze", weapon_type="natural"),
    Weapon(name="Black Flame", weapon_type="natural"),
    Weapon(name="Bane Touch", weapon_type="natural"),
    Weapon(name="Death Lash", weapon_type="natural"),
    Weapon(name="Nightmare Breath", weapon_type="natural"),
    Weapon(name="Doom Spike", weapon_type="natural"),
    Weapon(name="Venomous Barb", weapon_type="natural"),
    Weapon(name="Blight Fang", weapon_type="natural"),
    Weapon(name="Hellish Claw", weapon_type="natural"),
    Weapon(name="Thunderous Roar", weapon_type="natural"),
    Weapon(name="Oblivion Claw", weapon_type="natural"),
    Weapon(name="Darkness Lash", weapon_type="natural"),
    Weapon(name="Crushing Gaze", weapon_type="natural"),
    Weapon(name="Soul Crusher", weapon_type="natural"),
    Weapon(name="Vile Touch", weapon_type="natural"),
    Weapon(name="Fell Fang", weapon_type="natural"),
    Weapon(name="Venom Strike", weapon_type="natural"),
    Weapon(name="Infernal Claws", weapon_type="natural"),
    Weapon(name="Dreadful Spines", weapon_type="natural"),
    Weapon(name="Hellhound Bite", weapon_type="natural"),
    Weapon(name="Plague Breath", weapon_type="natural"),
    Weapon(name="Spectral Lash", weapon_type="natural"),
    Weapon(name="Scalding Flame", weapon_type="natural"),
    Weapon(name="Dark Maul", weapon_type="natural"),
    Weapon(name="Cursed Flame", weapon_type="natural"),
    Weapon(name="Unholy Claws", weapon_type="natural"),
    Weapon(name="Warped Spike", weapon_type="natural"),
    Weapon(name="Chilling Gaze", weapon_type="natural"),
    Weapon(name="Blighted Breath", weapon_type="natural"),
    Weapon(name="Warped Fang", weapon_type="natural"),
    Weapon(name="Toxic Grasp", weapon_type="natural"),
    Weapon(name="Infernal Slash", weapon_type="natural"),
    Weapon(name="Demonic Roar", weapon_type="natural"),
    Weapon(name="Rift Bite", weapon_type="natural"),
    Weapon(name="Cursed Touch", weapon_type="natural"),
    Weapon(name="Nether Claw", weapon_type="natural"),
    Weapon(name="Wraith's Grasp", weapon_type="natural"),
    Weapon(name="Obsidian Spines", weapon_type="natural"),
    Weapon(name="Hellish Maw", weapon_type="natural"),
    Weapon(name="Blazing Bite", weapon_type="natural"),
    Weapon(name="Necrotic Screech", weapon_type="natural"),
    Weapon(name="Shadow Spike", weapon_type="natural"),
    Weapon(name="Spectral Fang", weapon_type="natural"),
    Weapon(name="Chilling Bite", weapon_type="natural"),
    Weapon(name="Darkfire Breath", weapon_type="natural"),
    Weapon(name="Warped Maul", weapon_type="natural"),
    Weapon(name="Gore Claw", weapon_type="natural"),
    Weapon(name="Crushing Roar", weapon_type="natural"),
    Weapon(name="Hellfire Claw", weapon_type="natural"),
    Weapon(name="Poison Spit", weapon_type="natural"),
    Weapon(name="Blackened Fang", weapon_type="natural"),
    Weapon(name="Void Touch", weapon_type="natural"),
    Weapon(name="Demonic Gaze", weapon_type="natural"),
    Weapon(name="Putrid Fang", weapon_type="natural"),
    Weapon(name="Eldritch Spike", weapon_type="natural"),
    Weapon(name="Terror Claws", weapon_type="natural"),
    Weapon(name="Soulbite", weapon_type="natural"),
    Weapon(name="Twisted Spines", weapon_type="natural"),
    Weapon(name="Warped Breath", weapon_type="natural")
]

high_tier_weapons = high_tier_weapons_norm + high_tier_weapons_nat